### ISSUE TITLE
Invalid public key for CUDA apt repository in Dockerfile_MSeg

### ISSUE THREAD

**Issue by ZGX010** [BonifazStuhr/feamgan#1]
InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC

**Comment by ZGX010** [comment]
refer to：
https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901/8

I modified the dockerfile as follows and solved this problem （line 2,3）：
`
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub 
`
before `RUN apt-get update `

**Comment by ZGX010** [comment]
And sklearn in requests.txt of mseg-semantic should be changed to scikit-learn 
change "line 16" in Dockerfile_MSeg  to my mseg-semantic project 
`RUN SHA=ToUcHMe git clone https://github.com/ZGX010/mseg-semantic.git`

or fix that by yourself in mseg-semantic project
scikit -> scikit-learn

**Comment by ZGX010** [comment]
Docker (mseg-semantic) problem has been solved

**Comment by BonifazStuhr** [comment]
Hello ZGX010,

thanks for pointing out the two problems! I have updated `Dockerfile_MSeg`, it should work now. 

Regarding the second problem with the mseg-semantic project, I also wrote an issue related to your post: https://github.com/mseg-dataset/mseg-semantic/issues/51.
